
import { Post, NavItem, Constructor } from './types';

export const NAV_ITEMS: NavItem[] = [
  { label: 'HOME', href: '#' },
  { label: 'TEAMS & FAHRER', href: '#' },
  { label: 'RENNKALENDER', href: '#' },
  { label: 'WM-STAND', href: '#' },
  { label: 'TIPPSPIEL', href: '#' },
];

export const BLOCK_SPACINGS: Record<string, string> = {
  'custom/paragraph': 'my-7',
  'custom/heading': 'my-7',
  'custom/list': 'my-7',
  'custom/quote': 'my-7',
  'custom/details': 'my-7',
  'custom/table': 'my-7',
  'custom/image': 'my-7',
  'custom/gallery': 'my-7',
  'custom/slider': 'my-7',
  'custom/youtube': 'my-7',
  'custom/spotify': 'my-7',
  'custom/separator': 'my-7',
  'custom/comment': 'my-7',
  'f1/driver': 'my-7',
  'f1/team': 'my-7',
  'f1/event': 'my-7',
  'f1/calendar': 'my-7',
  'f1/standings': 'my-7',
  'f1/results': 'my-7',
  'f1/title-watch': 'my-7'
};

export const COUNTRIES = [
    { name: 'Afghanistan', code: 'af' },
    { name: 'Ägypten', code: 'eg' },
    { name: 'Albanien', code: 'al' },
    { name: 'Algerien', code: 'dz' },
    { name: 'Andorra', code: 'ad' },
    { name: 'Argentinien', code: 'ar' },
    { name: 'Armenien', code: 'am' },
    { name: 'Aserbaidschan', code: 'az' },
    { name: 'Australien', code: 'au' },
    { name: 'Bahrain', code: 'bh' },
    { name: 'Belgien', code: 'be' },
    { name: 'Bolivien', code: 'bo' },
    { name: 'Bosnien und Herzegowina', code: 'ba' },
    { name: 'Brasilien', code: 'br' },
    { name: 'Bulgarien', code: 'bg' },
    { name: 'Chile', code: 'cl' },
    { name: 'China', code: 'cn' },
    { name: 'Costa Rica', code: 'cr' },
    { name: 'Dänemark', code: 'dk' },
    { name: 'Deutschland', code: 'de' },
    { name: 'Dominikanische Republik', code: 'do' },
    { name: 'Ecuador', code: 'ec' },
    { name: 'Estland', code: 'ee' },
    { name: 'Finnland', code: 'fi' },
    { name: 'Frankreich', code: 'fr' },
    { name: 'Georgien', code: 'ge' },
    { name: 'Griechenland', code: 'gr' },
    { name: 'Großbritannien', code: 'gb' },
    { name: 'Guatemala', code: 'gt' },
    { name: 'Honduras', code: 'hn' },
    { name: 'Hongkong', code: 'hk' },
    { name: 'Indien', code: 'in' },
    { name: 'Indonesien', code: 'id' },
    { name: 'Irland', code: 'ie' },
    { name: 'Island', code: 'is' },
    { name: 'Israel', code: 'il' },
    { name: 'Italien', code: 'it' },
    { name: 'Jamaika', code: 'jm' },
    { name: 'Japan', code: 'jp' },
    { name: 'Kanada', code: 'ca' },
    { name: 'Katar', code: 'qa' },
    { name: 'Kolumbien', code: 'co' },
    { name: 'Kroatien', code: 'hr' },
    { name: 'Kuba', code: 'cu' },
    { name: 'Lettland', code: 'lv' },
    { name: 'Liechtenstein', code: 'li' },
    { name: 'Litauen', code: 'lt' },
    { name: 'Luxemburg', code: 'lu' },
    { name: 'Malaysia', code: 'my' },
    { name: 'Malta', code: 'mt' },
    { name: 'Marokko', code: 'ma' },
    { name: 'Mexiko', code: 'mx' },
    { name: 'Moldawien', code: 'md' },
    { name: 'Monaco', code: 'mc' },
    { name: 'Montenegro', code: 'me' },
    { name: 'Neuseeland', code: 'nz' },
    { name: 'Niederlande', code: 'nl' },
    { name: 'Nordmazedonien', code: 'mk' },
    { name: 'Norwegen', code: 'no' },
    { name: 'Österreich', code: 'at' },
    { name: 'Pakistan', code: 'pk' },
    { name: 'Panama', code: 'pa' },
    { name: 'Paraguay', code: 'py' },
    { name: 'Peru', code: 'pe' },
    { name: 'Philippinen', code: 'ph' },
    { name: 'Polen', code: 'pl' },
    { name: 'Portugal', code: 'pt' },
    { name: 'Puerto Rico', code: 'pr' },
    { name: 'Rumänien', code: 'ro' },
    { name: 'Russland', code: 'ru' },
    { name: 'Saudi-Arabien', code: 'sa' },
    { name: 'Schweden', code: 'se' },
    { name: 'Schweiz', code: 'ch' },
    { name: 'Serbien', code: 'rs' },
    { name: 'Singapur', code: 'sg' },
    { name: 'Slowakei', code: 'sk' },
    { name: 'Slowenien', code: 'si' },
    { name: 'Spanien', code: 'es' },
    { name: 'Südafrika', code: 'za' },
    { name: 'Südkorea', code: 'kr' },
    { name: 'Taiwan', code: 'tw' },
    { name: 'Thailand', code: 'th' },
    { name: 'Tschechien', code: 'cz' },
    { name: 'Türkei', code: 'tr' },
    { name: 'Ukraine', code: 'ua' },
    { name: 'Ungarn', code: 'hu' },
    { name: 'Uruguay', code: 'uy' },
    { name: 'USA', code: 'us' },
    { name: 'Venezuela', code: 've' },
    { name: 'Vereinigte Arabische Emirate', code: 'ae' },
    { name: 'Vietnam', code: 'vn' },
    { name: 'Zypern', code: 'cy' },
];

export const getFlagUrl = (code: string | undefined) => {
    if (!code) return '';
    // Check if it's already a full URL (legacy support) or emoji
    if (code.startsWith('http') || code.length > 3) return ''; 
    return `https://flagcdn.com/${code.toLowerCase()}.svg`;
};

// Initial Data for placeholders (legacy removed)
export const DRIVERS = [];
export const CONSTRUCTORS: Constructor[] = [];
export const INITIAL_POSTS: Post[] = [
  {
    id: 'hero-1',
    title: "Ab 2026 gilt 'ne andere Formel: Leichter, schlanker, elektrischer.",
    author: 'Sascha Riefe',
    date: '20.12.2025',
    image: 'https://picsum.photos/800/600?random=1',
    tags: ['Aktuell', 'Ausgewählt', 'Beliebt', 'Im Trend', 'Top News', 'Updated'],
    commentCount: 0,
    readTime: '3 minutes read',
    section: ['highlight', 'feed'],
    status: 'published',
    content: "Dies ist der Hauptartikel...",
    blocks: [
      { clientId: 'b1', type: 'custom/paragraph', attributes: { content: "Die Formel 1 steht vor ihrer größten Revolution. Ab 2026 ändern sich die Regeln drastisch." }, innerBlocks: [] },
      { clientId: 'b2', type: 'custom/heading', attributes: { level: 2, content: "Was ändert sich am Motor?" }, innerBlocks: [] },
      { clientId: 'b3', type: 'custom/paragraph', attributes: { content: "Die MGU-H fällt weg, dafür wird der elektrische Anteil auf fast 50% erhöht. Das bedeutet mehr Drehmoment, aber auch neue Herausforderungen für die Fahrer." }, innerBlocks: [] }
    ]
  },
  {
    id: 'rp-1',
    title: "Ne neue Nummer! Warum Startnummern 2026 mehr erzählen.",
    author: 'Sascha Riefe',
    date: '20.12.2025',
    image: 'https://picsum.photos/100/100?random=2',
    tags: [],
    commentCount: 0,
    readTime: '2 min',
    section: ['aktuell'],
    status: 'published',
    blocks: []
  },
  {
    id: 'rp-2',
    title: "Audi und die Revolut(ion): Der große F1-Einstieg der vier Ringe.",
    author: 'Sascha Riefe',
    date: '31.01.2026',
    image: 'https://picsum.photos/100/100?random=3',
    tags: [],
    commentCount: 0,
    readTime: '4 min',
    section: ['aktuell', 'ausgewählt'],
    status: 'published',
    blocks: []
  },
  {
    id: 'rp-3',
    title: "Supermax: Auch ohne die Krone neue Maßstäbe gesetzt!",
    author: 'Sascha Riefe',
    date: '20.12.2025',
    image: 'https://picsum.photos/100/100?random=4',
    tags: [],
    commentCount: 0,
    readTime: '3 min',
    section: ['aktuell'],
    status: 'published',
    blocks: []
  },
  {
    id: 'rp-4',
    title: "Das perfekte Weihnachtsgeschenk für Formel-1-Fans.",
    author: 'Sascha Riefe',
    date: '20.12.2025',
    image: 'https://picsum.photos/100/100?random=5',
    tags: [],
    commentCount: 0,
    readTime: '1 min',
    section: ['aktuell'],
    status: 'published',
    blocks: []
  },
  {
    id: 'tp-1',
    title: "Updated: Lando Norris dominiert in Silverstone!",
    author: 'Redaktion',
    date: '20.12.2025',
    image: 'https://picsum.photos/100/100?random=6',
    tags: ['Updated'],
    commentCount: 1,
    readTime: '2 min',
    section: ['updated'],
    status: 'published',
    blocks: []
  },
  {
    id: 'tp-2',
    title: "Das perfekte Weihnachtsgeschenk für Formel-1-Fans.",
    author: 'Redaktion',
    date: '20.12.2025',
    image: 'https://picsum.photos/100/100?random=7',
    tags: ['Geschenke'],
    commentCount: 0,
    readTime: '1 min',
    section: ['trending'],
    status: 'published',
    blocks: []
  },
  {
    id: 'tp-3',
    title: "Zeit als Maßstab: 75 Jahre Formel 1 mit Uhren von TAG Heuer.",
    author: 'Redaktion',
    date: '20.12.2025',
    image: 'https://picsum.photos/100/100?random=8',
    tags: ['Historie'],
    commentCount: 0,
    readTime: '5 min',
    section: ['trending'],
    status: 'published',
    blocks: []
  },
  {
    id: 'tp-4',
    title: "Ne neue Nummer! Warum Startnummern 2026 mehr erzählen.",
    author: 'Redaktion',
    date: '20.12.2025',
    image: 'https://picsum.photos/100/100?random=9',
    tags: ['Analyse'],
    commentCount: 0,
    readTime: '3 min',
    section: ['trending'],
    status: 'published',
    blocks: []
  },
  {
    id: 'gp-1',
    title: "Zeit als Maßstab: 75 Jahre Formel 1 mit Uhren von TAG Heuer.",
    author: 'Sascha Riefe',
    date: '20.12.2025',
    image: 'https://picsum.photos/600/400?random=10',
    tags: ['Ausgewählt', 'Beliebt', 'Im Trend'],
    commentCount: 0,
    readTime: '3 minutes read',
    section: ['ausgewählt', 'feed'],
    status: 'published',
    blocks: []
  },
  {
    id: 'gp-2',
    title: "Ne neue Nummer! Warum Startnummern 2026 mehr erzählen.",
    author: 'Sascha Riefe',
    date: '20.12.2025',
    image: 'https://picsum.photos/600/400?random=11',
    tags: ['Aktuell', 'Ausgewählt', 'Im Trend'],
    commentCount: 0,
    readTime: '3 minutes read',
    section: ['ausgewählt'],
    status: 'published',
    blocks: []
  },
  {
    id: 'gp-3',
    title: "Audi und die Revolut(ion): Der große F1-Einstieg der vier Ringe.",
    author: 'Sascha Riefe',
    date: '31.01.2026',
    image: 'https://picsum.photos/600/400?random=12',
    tags: ['Aktuell', 'Ausgewählt', 'Beliebt', 'Im Trend'],
    commentCount: 0,
    readTime: '3 minutes read',
    section: ['ausgewählt'],
    status: 'published',
    blocks: []
  },
  {
    id: 'gp-4',
    title: "Supermax: Auch ohne die Krone neue Maßstäbe gesetzt!",
    author: 'Sascha Riefe',
    date: '20.12.2025',
    image: 'https://picsum.photos/600/400?random=13',
    tags: ['Aktuell', 'Ausgewählt', 'Beliebt', 'Im Trend'],
    commentCount: 2,
    readTime: '2 minutes read',
    section: ['ausgewählt'],
    status: 'published',
    blocks: []
  },
  {
    id: 'fp-1',
    title: "Zeit als Maßstab: 75 Jahre Formel 1 mit Uhren von TAG Heuer.",
    excerpt: "Warum TAG Heuer und die Formel 1 seit 75 Jahren dieselbe Sprache sprechen Zeit ist in der Formel 1 kein abstrakter Begriff. Sie ist brutal konkret. Tausendstel entscheiden über Startplätze, Strategien, Karrieren. Wer sie nicht kontrolliert, verliert. Vielleicht ist genau das der Grund, warum sich die Wege von TAG Heuer und der Formel 1 schon früh gekreuzt haben - lange bevor Luxuhren Statussymbole wurden...",
    author: 'Sascha Riefe',
    date: '20.12.2025',
    image: 'https://picsum.photos/600/400?random=14',
    tags: ['Ausgewählt', 'Beliebt', 'Im Trend'],
    commentCount: 0,
    readTime: '3 minutes read',
    section: ['feed'],
    status: 'published',
    content: "Full content here...",
    blocks: []
  },
  {
    id: 'fp-2',
    title: "Ne neue Nummer! Warum Startnummern 2026 mehr erzählen.",
    excerpt: "Mit dem Ende der Saison 2025 rückt ein kleines, aber symbolisch starkes detail immer mehr in den Fokus: die Startnummern der Formel-1-Fahrer. In der kommenden Saison wird Weltmeister Lando Norris erstmals mit der Startnummer 1 antreten, während **Max Verstappen nach dem Verlust seines WM-Titels von 2025 auf Nummer 3 wechselt...",
    author: 'Sascha Riefe',
    date: '20.12.2025',
    image: 'https://picsum.photos/600/400?random=15',
    tags: ['Aktuell', 'Ausgewählt', 'Im Trend'],
    commentCount: 0,
    readTime: '3 minutes read',
    section: ['feed'],
    status: 'published',
    blocks: []
  },
  {
    id: 'fp-3',
    title: "Audi und die Revolut(ion): Der große F1-Einstieg der vier Ringe.",
    excerpt: "Nach Jahren der Vorbereitung steht Audi unmittelbar vor dem offiziellen Debüt in der Formel 1-Weltmeisterschaft 2026. Ein Meilenstein für die Marke mit den vier Ringen und für den deutschen Motorsport insgesamt. Teamname, Logo & Launch-Event Audi hat den Namen und das Logo seines Formel-1-Werksteams bekanntgegeben: „Audi Revolut F1 Team“...",
    author: 'Sascha Riefe',
    date: '31.01.2026',
    image: 'https://picsum.photos/600/400?random=16',
    tags: ['Aktuell', 'Ausgewählt', 'Beliebt', 'Im Trend'],
    commentCount: 0,
    readTime: '3 minutes read',
    section: ['feed'],
    status: 'published',
    blocks: []
  },
  {
    id: 'fp-4',
    title: "Supermax: Auch ohne die Krone neue Maßstäbe gesetzt!",
    excerpt: "Max Verstappen blickt auf die Saison 2025 zurück, die er im Titelkampf der fahrer-Weltmeisterschaft nur um zwei Punkte verlor. Trotz des knapp verpassten fünften Weltmeistertitels hat Max Verstappen die Formel-1-Saison 2025 als die beste seiner bisherigen Karriere bezeichnet...",
    author: 'Sascha Riefe',
    date: '20.12.2025',
    image: 'https://picsum.photos/600/400?random=17',
    tags: ['Aktuell', 'Ausgewählt', 'Beliebt', 'Im Trend'],
    commentCount: 0,
    readTime: '2 minutes read',
    section: ['feed'],
    status: 'published',
    blocks: []
  }
];
